---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: Há vários requisitos de hardware e questões de planejamento que você deve considerar relacionados ao ambiente VMware. 
---
= Considerações sobre o hipervisor e hardware do ONTAP Select VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há vários requisitos de hardware e questões de planejamento que você deve considerar relacionados ao ambiente VMware.



== Requisitos do hipervisor

Há vários requisitos relacionados ao hipervisor onde o ONTAP Select é executado.


NOTE: Você deve revisar as notas de versão atuais da sua versão do ONTAP Select para verificar se há restrições ou limitações adicionais conhecidas.



=== Licenciamento VMware

Para implantar um cluster ONTAP Select , sua organização precisa ter uma licença válida do VMware vSphere para os hosts do hipervisor onde o ONTAP Select é executado. Você deve usar as licenças apropriadas para sua implantação.



=== Compatibilidade de software

O ONTAP Select pode ser implantado nos seguintes hipervisores:

* KVM no Red Hat Enterprise Linux 8.6, 8.7, 8.8, 9.0, 9.1, 9.2, 9.4 e 9.5
* KVM no Rocky Linux 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2, 9.3, 9.4 e 9.5
* VMware ESXi 7.0 GA (compilação 15843807 ou superior), incluindo 7.0 U1, U2 e U3C
* VMware ESXi 8.0 GA (compilação 20513097)
* VMware ESXi 8.0 U1 (compilação 21495797)
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U3



NOTE: O NetApp oferece suporte ao ONTAP Select nas versões identificadas do ESXi, desde que a VMware também continue a oferecer suporte às mesmas versões.


NOTE: O ESXi 6.5 GA e o ESXi 6.7 GA atingiram o fim do status de disponibilidade. Se você tiver clusters ONTAP Select com essas versões, deverá atualizar para as versões compatíveis, conforme as instruções.  https://mysupport.netapp.com/matrix["Ferramenta de Matriz de Interoperabilidade (IMT)"^] .



=== VMware vCenter e hosts ESXi autônomos

Se um host do hipervisor ESXi for gerenciado por um servidor vCenter, você deverá registrá-lo no utilitário de administração de implantação usando as credenciais do vCenter. Não é possível registrar o host como um host autônomo usando as credenciais do ESXi.



== Requisitos de hardware principais

O host do hipervisor físico onde você implanta o ONTAP Select deve atender a diversos requisitos de hardware. Você pode escolher qualquer plataforma para o host do hipervisor, desde que ela atenda aos requisitos mínimos de hardware. Os seguintes fornecedores oferecem plataformas de hardware compatíveis: Cisco, Dell, HP, Fujitsu, Lenovo e Supermicro.


NOTE: A partir do ONTAP Select 9.9.1, somente modelos de CPU baseados no Intel Xeon Sandy Bridge ou posterior são suportados.

Consulte o  https://mysupport.netapp.com/matrix["Ferramenta de Matriz de Interoperabilidade,window=_blank"] para maiores informações.



=== Requisitos básicos de hardware

Existem vários requisitos comuns de hardware que se aplicam a todas as plataformas, independentemente do tipo de instância do nó ou da oferta de licença.

.Processador
Os microprocessadores suportados incluem o seguinte:

* Processadores Intel Xeon para servidor (consulte link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Processadores Intel Xeon,window=_blank"] para mais informações)



NOTE: Os processadores Advanced Micro Devices (AMD) não são suportados pelo ONTAP Select.

.Configuração Ethernet
Há várias configurações Ethernet suportadas com base no tamanho do cluster.

[cols="30,35,35"]
|===


| Tamanho do cluster | Requisitos mínimos | Requisitos recomendados 


| Cluster de nó único | 2 x 1GbE | 2 x 10GbE 


| Cluster de dois nós ou MetroCluster SDS | 4 x 1GbE ou 1 x 10GbE | 2 x 10GbE 


| Agrupamento de 4/6/8 nós | 2 x 10GbE | 4 x 10GbE ou 2 x 25/40GbE 
|===


=== Requisitos adicionais de hardware com base no tipo de instância

Há vários requisitos de hardware adicionais com base no tipo de instância do nó.

Consulte link:concept_lic_platforms.html["Entenda as ofertas de licenças de plataforma"] para maiores informações.

.Pequeno
* Núcleos de CPU Seis núcleos físicos ou mais, com quatro reservados para o ONTAP Select.
* Memória de 24 GB ou mais, com 16 GB reservados para ONTAP Select.
* Licença de plataforma necessária oferecendo Standard, premium ou premium XL


.Médio
* Núcleos de CPU Dez núcleos físicos ou mais, com oito reservados para ONTAP Select.
* Memória de 72 GB ou mais com 64 GB reservados para ONTAP Select
* Licença de plataforma necessária oferecendo Premium ou Premium XL


.Grande
* Núcleos de CPU Dezoito núcleos físicos ou mais, com dezesseis reservados para o ONTAP Select.
* Memória de 136 GB ou superior com 128 GB reservados para ONTAP Select
* Licença de plataforma necessária oferecendo Premium XL



NOTE: Há requisitos de disco adicionais com base na licença da plataforma. Ver link:reference_plan_ots_storage.html["Armazenamento e RAID"] para maiores informações.
