---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: A versão atual inclui vários novos recursos ou melhorias específicas do ONTAP Select. 
---
= Novidades do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre os novos recursos e aprimoramentos nas versões suportadas do ONTAP Select.



== ONTAP Select 9.16.1

O ONTAP Select 9.16.1 inclui vários novos recursos e melhorias.

Suporte atualizado ao arquivo de licença NetApp:: A partir do ONTAP Select 9.16.1, o suporte ao Arquivo de Licença NetApp (NLF) foi atualizado. O novo formato NLF inclui licenças para os recursos ARP, ONTAP S3 e S3 SnapMirror . link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saber mais"] .
+
--
Para uma nova implantação do ONTAP Select 9.16.1, o novo formato NLF é aplicado automaticamente. Ao atualizar uma implantação do ONTAP Select existente para a versão 9.16.1, o novo formato NLF não é aplicado. Para obter as licenças de recursos do ARP, ONTAP S3 e S3 SnapMirror , você precisa baixar o NLF atualizado após a atualização. Se você reverter para o ONTAP Select 9.15.1 ou anterior, precisará reinstalar as licenças de recursos que tinha antes da atualização.

--
Suporte para proteção autônoma contra ransomware:: O ONTAP Select 9.16.1 introduz suporte para Proteção Autônoma contra Ransomware (ARP). O ONTAP Select 9.16.1 suporta apenas atualizações manuais para ARP, atualizações automáticas não são suportadas. A licença do recurso ARP está incluída no NLF do ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saber mais"] .
Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.16.1 inclui suporte para VMware ESXi 8.0 U3.
Suporte atualizado ao hipervisor KVM:: A partir do ONTAP Select 9.16.1, o hipervisor de máquina virtual baseada em kernel (KVM) é compatível com o Red Hat Enterprise Linux (RHEL) 9.5 e o Rocky Linux 9.5.




== ONTAP Select 9.15.1

O ONTAP Select 9.15.1 inclui vários novos recursos e melhorias.

Suporte atualizado ao hipervisor KVM:: A partir do ONTAP Select 9.15.1, o hipervisor de máquina virtual baseada em kernel (KVM) é compatível com RHEL 9.4 e Rocky Linux 9.4.
Apoio à expansão e contração de clusters:: A partir do ONTAP Select 9.15.1, a expansão e a contração de cluster são suportadas.
+
--
* Expansão de cluster de seis para oito nós
+
Você pode aumentar o tamanho do cluster de seis para oito nós com o recurso de expansão de cluster. Expansões de cluster de um, dois ou quatro nós para seis ou oito nós não são suportadas atualmente. link:task_cluster_expansion_contraction.html#expand-the-cluster["Saber mais"] .

* Contração de cluster de oito a seis nós
+
Você pode reduzir o tamanho do cluster de oito para seis nós com o recurso de contração de cluster. Atualmente, não há suporte para contrações de clusters de seis ou oito nós para clusters de um, dois ou quatro nós. link:task_cluster_expansion_contraction.html#contract-the-cluster["Saber mais"] .



--



NOTE: O suporte para expansão e contração de clusters é limitado somente a clusters ESX.



== ONTAP Select 9.14.1

O ONTAP Select 9.14.1 inclui vários novos recursos e melhorias.

Suporte para hipervisor KVM:: A partir do ONTAP Select 9.14.1, o suporte ao hipervisor KVM foi restabelecido. Anteriormente, o suporte para a implantação de um novo cluster em um hipervisor KVM foi removido no ONTAP Select 9.10.1, e o suporte para o gerenciamento de clusters e hosts KVM existentes, exceto para desativá-los ou excluí-los, foi removido no ONTAP Select 9.11.1.
A implantação do plug-in VMware vCenter não é mais suportada:: A partir do ONTAP Select 9.14.1, o plug-in Deploy VMware vCenter não é mais suportado.
Suporte atualizado ao ONTAP Select Deploy:: Se você estiver executando uma versão do ONTAP Select Deploy 9.14.1 anterior à 9.14.1P2, atualize para o ONTAP Select Deploy 9.14.1P2 o mais rápido possível. Para obter mais informações, consulte o link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .
Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.14.1 inclui suporte para VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

O ONTAP Select 9.13.1 inclui vários novos recursos e melhorias.

Suporte para NVMe sobre TCP:: Ao atualizar para o ONTAP Select 9.13.1, você precisa ter a nova licença para oferecer suporte a NVMe sobre TCP. Esta licença é incluída automaticamente ao implantar o ONTAP Select pela primeira vez a partir da versão 9.13.1.
Suporte VMware ESXi atualizado:: A partir do ONTAP 9.13.1, o VMware ESXi 8.0.1 GA (compilação 20513097) é compatível com a versão de hardware 4 e posteriores.
Suporte atualizado ao ONTAP Select Deploy:: A partir de abril de 2024, o ONTAP Select Deploy 9.13.1 não estará mais disponível no site de suporte da NetApp . Se você estiver executando o ONTAP Select Deploy 9.13.1, atualize para o ONTAP Select Deploy 9.14.1P2 o mais breve possível. Para obter mais informações, consulte o link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .




== ONTAP Select 9.12.1

O ONTAP Select 9.12.1 se beneficia da maioria dos novos desenvolvimentos da versão atual do produto principal do ONTAP . Ele não inclui novos recursos ou melhorias específicas do ONTAP Select.

A partir de abril de 2024, o ONTAP Select Deploy 9.12.1 não estará mais disponível no site de suporte da NetApp . Se você estiver executando o ONTAP Select Deploy 9.12.1, atualize para o ONTAP Select Deploy 9.14.1P2 o mais breve possível. Para obter mais informações, consulte o link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de versão do ONTAP Select 9.14.1"^] .



== ONTAP Select 9.11.1

O ONTAP Select 9.11.1 inclui vários novos recursos e melhorias.

Suporte aprimorado ao VMware ESXi:: O ONTAP Select 9.11.1 inclui suporte para VMware ESXi 7.0 U3C.
Suporte para VMware NSX-T:: O ONTAP Select 9.10.1 e versões posteriores foram qualificados para o VMware NSX-T versão 3.1.2. Não há problemas funcionais ou deficiências ao usar o NSX-T com um cluster de nó único do ONTAP Select implantado com um arquivo OVA e o utilitário de administração ONTAP Select Deploy. No entanto, ao usar o NSX-T com um cluster de vários nós do ONTAP Select , observe a seguinte limitação do ONTAP Select 9.11.1:
+
--
* Verificador de conectividade de rede
+
O verificador de conectividade de rede disponível por meio do Deploy CLI falha quando executado em uma rede baseada em NSX-T.



--
O hipervisor KVM não é mais suportado::
+
--
* A partir do ONTAP Select 9.10.1, não é mais possível implantar um novo cluster no hipervisor KVM.
* A partir do ONTAP Select 9.11.1, todas as funcionalidades de gerenciamento não estão mais disponíveis para clusters e hosts KVM existentes, exceto as funções de desativação e exclusão.
+
A NetApp recomenda fortemente que os clientes planejem e executem uma migração completa de dados do ONTAP Select para KVM para qualquer outra plataforma ONTAP , incluindo o ONTAP Select para ESXi. Para obter mais informações, consulte  https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Aviso de EOA"^]



--




== ONTAP Select 9.10.1

O ONTAP Select 9.10.1 inclui vários novos recursos e melhorias.

Suporte para VMware NSX-T:: O ONTAP Select 9.10.1 foi qualificado para o VMware NSX-T versão 3.1.2. Não há problemas ou deficiências funcionais ao usar o NSX-T com um cluster de nó único do ONTAP Select implantado com um arquivo OVA e o utilitário de administração ONTAP Select Deploy. No entanto, ao usar o NSX-T com um cluster de vários nós do ONTAP Select , observe os seguintes requisitos e limitações:
+
--
* MTU de cluster
+
Você deve ajustar manualmente o tamanho da MTU do cluster para 8.800 antes de implantar o cluster para compensar a sobrecarga adicional. A orientação da VMware é permitir um buffer de 200 bytes ao usar o NSX-T.

* Configuração de rede 4x10Gb
+
Para implantações do ONTAP Select em um host VMware ESXi configurado com quatro NICs, o utilitário de implantação solicitará que você siga a prática recomendada de dividir o tráfego interno em dois grupos de portas diferentes e o tráfego externo em dois grupos de portas diferentes. No entanto, ao usar uma rede sobreposta, essa configuração não funciona e você deve desconsiderar a recomendação. Nesse caso, você deve usar apenas um grupo de portas internas e um grupo de portas externas.

* Verificador de conectividade de rede
+
O verificador de conectividade de rede disponível por meio do Deploy CLI falha quando executado em uma rede baseada em NSX-T.



--
O hipervisor KVM não é mais suportado:: A partir do ONTAP Select 9.10.1, não é mais possível implantar um novo cluster no hipervisor KVM. No entanto, se você atualizar um cluster de uma versão anterior para a 9.10.1, ainda poderá usar o utilitário de implantação para administrá-lo.




== ONTAP Select 9.9.1

O ONTAP Select 9.9.1 inclui vários novos recursos e melhorias.

Suporte à família de processadores:: A partir do ONTAP Select 9.9.1, somente modelos de CPU Intel Xeon Sandy Bridge ou posterior são suportados pelo ONTAP Select.
Suporte VMware ESXi atualizado:: O suporte ao VMware ESXi foi aprimorado com o ONTAP Select 9.9.1. As seguintes versões agora são suportadas:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

Há vários recursos novos e alterados incluídos no ONTAP Select 9.8.

Interface de alta velocidade:: O recurso de interface de alta velocidade aprimora a conectividade de rede, oferecendo opções para 25G (25GbE) e 40G (40GbE). Para obter o melhor desempenho ao usar essas velocidades mais altas, siga as práticas recomendadas para configurações de mapeamento de portas, conforme descrito na documentação do ONTAP Select .
Suporte VMware ESXi atualizado:: Há duas mudanças no ONTAP Select 9.8 em relação ao suporte ao VMware ESXi.
+
--
* O ESXi 7.0 é compatível (compilação GA 15843807 e posterior)
* O ESXi 6.0 não é mais suportado


--

