---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partir do ONTAP Select 9.15.1, você pode aumentar o tamanho de um cluster existente de seis para oito nós e diminuir o tamanho do cluster de oito para seis nós. 
---
= Expandir ou contrair um cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir do ONTAP Select 9.15.1, você pode aumentar o tamanho de um cluster existente de seis para oito nós e diminuir o tamanho do cluster de oito para seis nós.

As seguintes expansões e contrações de cluster não são suportadas:

* Expansões de clusters de um, dois ou quatro nós para clusters de seis ou oito nós.
* Contrações de aglomerados de seis ou oito nós para aglomerados de um, dois ou quatro nós.


[NOTE]
====
Para alterar o número de nós em um cluster para um tamanho que não é suportado pela expansão ou contração do cluster, você precisa executar as seguintes tarefas:

. Implante um novo cluster de vários nós usando o link:task_cli_deploy_cluster.html["CLI"] ou o link:task_deploy_cluster.html["interface da web"] fornecido com o utilitário de administração ONTAP Select Deploy.
. Se aplicável, migre os dados para o novo cluster usando link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replicação SnapMirror"^] .


====
Você inicia os procedimentos de expansão e contração do cluster no ONTAP Select Deploy usando a CLI, a API ou a interface da web.



== Considerações sobre hardware e armazenamento

As funcionalidades de expansão e contração do cluster são restritas das seguintes maneiras:

* O suporte é limitado a clusters criados em hosts de hipervisor ESX. As seguintes versões do ESX são compatíveis com o ONTAP Select 9.15.1 e posteriores:
+
** ESXi 8.0 U3
** ESXi 8.0 U2
** ESXi 8.0 U1
** ESXi 8.0 GA
** ESXi 7.0 U3
** ESXi 7.0






== Expandir o cluster

Você pode aumentar o tamanho de um cluster existente de seis nós para um cluster de oito nós com o recurso de expansão de cluster.

.Sobre esta tarefa
Em preparação para o procedimento de expansão do cluster, novos hosts ESX são adicionados ao inventário e os detalhes dos novos nós são atribuídos. Antes de iniciar o processo de expansão do cluster, uma pré-verificação de rede verifica a rede interna selecionada.

.Antes de começar
* Ao implantar um cluster de vários nós, você deve estar familiarizado com o verificador de conectividade de rede. Você pode executar o verificador de conectividade de rede usando o link:task_adm_connectivity.html["interface da web"] ou o link:task_cli_connectivity.html["CLI"] .
* Verifique se você tem os detalhes da licença para os novos nós.


.Passos
. Sign in na interface de usuário da Web do utilitário Deploy usando a conta de administrador.
. Selecione a aba *Cluster* na parte superior da página e selecione o cluster desejado na lista.
. Na página de detalhes do cluster, selecione o ícone de engrenagem à direita da página e selecione *Expandir cluster*.
. Navegue até a seção *HA Par 4*.
. Escolha os detalhes de configuração do par de alta disponibilidade (HA) para o quarto par de HA, incluindo:
+
** Tipo de instância
** Nomes de nós
** Hosts de hipervisor associados
** Endereços IP do nó
** Licenças
** Configuração de rede
** Configuração de armazenamento (tipo RAID e pools de armazenamento)


. Selecione *Salvar par HA* para salvar os detalhes da configuração.
. Forneça as credenciais do ONTAP e selecione *Expandir cluster*.
. Selecione *Avançar* e execute a pré-verificação da rede selecionando *Executar*.
+
A pré-verificação da rede valida se a rede interna selecionada para o tráfego do cluster ONTAP está funcionando corretamente.

. Selecione *Expandir Cluster* para iniciar o processo de expansão do cluster e, em seguida, selecione *OK* na caixa de diálogo.
+
Pode levar até 45 minutos para que o cluster seja expandido.

. Monitore o processo de expansão do cluster em várias etapas para confirmar se o cluster foi expandido com sucesso.
. Consulte a aba *Eventos* para atualizações periódicas sobre o andamento da operação. A página é atualizada automaticamente em intervalos regulares.


.Depois que você terminar
Após expandir o cluster, você deve fazer backup dos dados de configuração do ONTAP Select Deploy.



== Contrair o cluster

Você pode diminuir o tamanho de um cluster existente de oito nós para seis nós com o recurso de contração de cluster.

.Sobre esta tarefa
O par de nós HA desejado no cluster é selecionado para preparar a contração do cluster durante o procedimento.

.Passos
. Sign in na interface de usuário da Web do utilitário Deploy usando a conta de administrador.
. Selecione a aba *Cluster* na parte superior da página e selecione o cluster desejado na lista.
. Na página de detalhes do cluster, selecione o ícone de engrenagem à direita da página e selecione *Cluster de contrato*.
. Selecione os detalhes de configuração do HA Pair para qualquer HA Pair que você deseja remover e forneça as credenciais do ONTAP . Em seguida, selecione *Contract Cluster*.
+
Pode levar até 30 minutos para que o cluster seja contratado.

. Monitore o processo de contração do cluster em várias etapas para confirmar se o cluster foi contraído com sucesso.
. Consulte a aba *Eventos* para atualizações periódicas sobre o andamento da operação. A página é atualizada automaticamente em intervalos regulares.

