---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Você pode adicionar uma imagem do ONTAP Select à sua instância do utilitário de administração Deploy. Após a instalação da imagem, você poderá usá-la ao implantar um cluster do ONTAP Select . 
---
= Adicionar uma imagem ONTAP Select para implantar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode adicionar uma imagem do ONTAP Select à sua instância do utilitário de administração Deploy. Após a instalação da imagem, você poderá usá-la ao implantar um cluster do ONTAP Select .



== Antes de começar

Em um nível alto, o processo usado para adicionar uma imagem ONTAP Select a uma instância do Deploy consiste em quatro etapas:

. Baixando a imagem de instalação
. Carregando a imagem de instalação para a máquina virtual Deploy
. Adicionando a imagem de instalação
. Exibindo as imagens de instalação disponíveis


Antes de adicionar novas imagens do ONTAP Select ao Deploy, você deve primeiro remover quaisquer imagens desnecessárias.


NOTE: Você só deve adicionar uma imagem do ONTAP Select com uma versão anterior à versão original incluída na sua instância do utilitário Deploy. Adicionar versões posteriores do ONTAP Select à medida que são disponibilizadas pela NetApp não é uma configuração suportada.



== Baixe a imagem de instalação

Para iniciar o processo de adição de uma imagem do ONTAP Select a uma instância do utilitário Deploy, você precisa baixar a imagem de instalação do site de suporte da NetApp . A imagem de instalação do ONTAP Select é formatada como um único arquivo compactado.

.Passos
. Acesse o site de suporte da NetApp usando um navegador da web e clique em *Links rápidos de suporte*.
. Clique em *Baixar software* em *Tarefas principais* e entre no site.
. Clique em *Encontre seu produto*.
. Role para baixo e clique em * ONTAP Select*.
. Em *Outro software selecionado disponível*, clique em *Implantar atualização, Atualização de nó, Instalação de imagem*.
. Selecione a versão desejada do pacote de atualização.
. Revise o Contrato de Licença do Usuário Final (CLUF) e clique em *Aceitar e Continuar*.
. Selecione e baixe o pacote apropriado, respondendo a todos os prompts conforme necessário para seu ambiente.




== Carregue a imagem de instalação para implantar

Após adquirir a imagem de instalação do ONTAP Select , você deve carregar o arquivo na máquina virtual Deploy.

.Antes de começar
Você precisa ter o arquivo de imagem de instalação disponível na sua estação de trabalho local. Você também precisa ter a senha da conta de usuário administrador do Deploy.

.Sobre esta tarefa
Esta tarefa descreve um método para enviar o arquivo para a máquina virtual de implantação. Pode haver outras opções mais adequadas ao seu ambiente.

.Etapa
. Em um shell de comando na sua estação de trabalho local, carregue o arquivo de imagem para a máquina virtual Deploy.
+
Exemplo

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Exemplo

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Resultado
O arquivo de instalação do nó é armazenado no diretório inicial do usuário administrador.



== Adicione a imagem de instalação

Você pode adicionar a imagem de instalação do ONTAP Select ao diretório de imagens de implantação para que ela esteja disponível ao implantar um novo cluster.

.Antes de começar
Você precisa saber em qual diretório o arquivo de imagem de instalação foi colocado na máquina virtual do utilitário de implantação. Presume-se que o arquivo esteja no diretório inicial do administrador.

.Passos
. Sign in na CLI do utilitário Deploy usando SSH com a conta de administrador (admin).
. Inicie o shell Bash:
+
`shell bash`

. Coloque o arquivo de imagem de instalação no diretório de imagens.
+
Exemplo 
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Exibir as imagens de instalação disponíveis

Você pode exibir as imagens do ONTAP Select que estão disponíveis ao implantar um novo cluster.

.Passos
. Acesse a página da documentação on-line na máquina virtual do utilitário Deploy e faça login usando a conta de administrador (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Use o nome de domínio ou endereço IP da máquina virtual de implantação.

. Navegue até o final da página e clique em *Implementar* e depois clique em *OBTER /imagens*.
. Clique em *Experimente!* para exibir as imagens disponíveis do ONTAP Select .
. Confirme se a imagem desejada está disponível.

